INSERT INTO Team(id, locationName, teamName, logoUri)
VALUES(1, 'New Jersey', 'Devils', 'https://nhllogos.blob.core.windows.net/nhl-logos/Avalanche.png'),
(2, 'New York', 'Islanders', 'https://nhllogos.blob.core.windows.net/nhl-logos/Islanders.png'),
(3, 'New York', 'Rangers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Rangers.png'),
(4, 'Philadelphia', 'Flyers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Flyers.png'),
(5, 'Pittsburgh', 'Penguins', 'https://nhllogos.blob.core.windows.net/nhl-logos/Penguins.png'),
(6, 'Boston', 'Bruins', 'https://nhllogos.blob.core.windows.net/nhl-logos/Bruins.png'),
(7, 'Buffalo', 'Sabres', 'https://nhllogos.blob.core.windows.net/nhl-logos/Sabres.png'),
(8, 'Montréal', 'Canadiens', 'https://nhllogos.blob.core.windows.net/nhl-logos/Canadiens.png'),
(9, 'Ottawa', 'Senators', 'https://nhllogos.blob.core.windows.net/nhl-logos/Senators.png'),
(10, 'Toronto', 'Maple Leafs', 'https://nhllogos.blob.core.windows.net/nhl-logos/Leafs.png'),
(12, 'Carolina', 'Hurricanes', 'https://nhllogos.blob.core.windows.net/nhl-logos/Hurricanes.png'),
(13, 'Florida', 'Panthers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Panthers.png'),
(14, 'Tampa Bay', 'Lightning', 'https://nhllogos.blob.core.windows.net/nhl-logos/Lightning.png'),
(15, 'Washington', 'Capitals', 'https://nhllogos.blob.core.windows.net/nhl-logos/Capitals.png'),
(16, 'Chicago', 'Blackhawks', 'https://nhllogos.blob.core.windows.net/nhl-logos/Blackhawks.png'),
(17, 'Detroit', 'Red Wings', 'https://nhllogos.blob.core.windows.net/nhl-logos/Red Wings.png'),
(18, 'Nashville', 'Predators', 'https://nhllogos.blob.core.windows.net/nhl-logos/Predators.png'),
(19, 'St. Louis', 'Blues', 'https://nhllogos.blob.core.windows.net/nhl-logos/Blues.png'),
(20, 'Calgary', 'Flames', 'https://nhllogos.blob.core.windows.net/nhl-logos/Flames.png'),
(21, 'Colorado', 'Avalanche', 'https://nhllogos.blob.core.windows.net/nhl-logos/Avalanche.png'),
(22, 'Edmonton', 'Oilers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Oilers.png'),
(23, 'Vancouver', 'Canucks', 'https://nhllogos.blob.core.windows.net/nhl-logos/Canucks.png'),
(24, 'Anaheim Ducks', 'https://nhllogos.blob.core.windows.net/nhl-logos/Ducks.png'),
(25, 'Dallas', 'Stars', 'https://nhllogos.blob.core.windows.net/nhl-logos/Stars.png'),
(26, 'Los Angeles', 'Kings', 'https://nhllogos.blob.core.windows.net/nhl-logos/Kings.png'),
(28, 'San Jose', 'Sharks', 'https://nhllogos.blob.core.windows.net/nhl-logos/Sharks.png'),
(29, 'Columbus', 'Blue Jackets', 'https://nhllogos.blob.core.windows.net/nhl-logos/Blue Jackets.png'),
(30, 'Minnesota', 'Wild', 'https://nhllogos.blob.core.windows.net/nhl-logos/Wild.png'),
(52, 'Winnipeg', 'Jets', 'https://nhllogos.blob.core.windows.net/nhl-logos/Jets.png'),
(53, 'Arizona', 'Coyotes', 'https://nhllogos.blob.core.windows.net/nhl-logos/Coyotes.png'),
(54, 'Vegas', 'Golden Knights', 'https://nhllogos.blob.core.windows.net/nhl-logos/Golden Knights.png'),
(55, 'Seattle', 'Kraken', 'https://nhllogos.blob.core.windows.net/nhl-logos/Kraken.png')