INSERT INTO Team(id, locationName, teamName, logoUri)
VALUES(1, 'New Jersey', 'Devils', 'https://nhllogos.blob.core.windows.net/nhl-logos/Avalanche.png'),
(2, 'New York', 'Islanders', 'https://nhllogos.blob.core.windows.net/nhl-logos/Islanders.png'),
(3, 'New York', 'Rangers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Rangers.png'),
(4, 'Philadelphia', 'Flyers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Flyers.png'),
(5, 'Pittsburgh', 'Penguins', 'https://nhllogos.blob.core.windows.net/nhl-logos/Penguins.png'),
(6, 'Boston', 'Bruins', 'https://nhllogos.blob.core.windows.net/nhl-logos/Bruins.png'),
(7, 'Buffalo', 'Sabres', 'https://nhllogos.blob.core.windows.net/nhl-logos/Sabres.png'),
(8, 'Montréal', 'Canadiens', 'https://nhllogos.blob.core.windows.net/nhl-logos/Canadiens.png'),
(9, 'Ottawa', 'Senators', 'https://nhllogos.blob.core.windows.net/nhl-logos/Senators.png'),
(10, 'Toronto', 'Maple Leafs', 'https://nhllogos.blob.core.windows.net/nhl-logos/MapleLeafs.png'),
(11, 'Atlanta', 'Thrashers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Thrashers.png'),
(12, 'Carolina', 'Hurricanes', 'https://nhllogos.blob.core.windows.net/nhl-logos/Hurricanes.png'),
(13, 'Florida', 'Panthers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Panthers.png'),
(14, 'Tampa Bay', 'Lightning', 'https://nhllogos.blob.core.windows.net/nhl-logos/Lightning.png'),
(15, 'Washington', 'Capitals', 'https://nhllogos.blob.core.windows.net/nhl-logos/Capitals.png'),
(16, 'Chicago', 'Blackhawks', 'https://nhllogos.blob.core.windows.net/nhl-logos/Blackhawks.png'),
(17, 'Detroit', 'Red Wings', 'https://nhllogos.blob.core.windows.net/nhl-logos/RedWings.png'),
(18, 'Nashville', 'Predators', 'https://nhllogos.blob.core.windows.net/nhl-logos/Predators.png'),
(19, 'St. Louis', 'Blues', 'https://nhllogos.blob.core.windows.net/nhl-logos/Blues.png'),
(20, 'Calgary', 'Flames', 'https://nhllogos.blob.core.windows.net/nhl-logos/Flames.png'),
(21, 'Colorado', 'Avalanche', 'https://nhllogos.blob.core.windows.net/nhl-logos/Avalanche.png'),
(22, 'Edmonton', 'Oilers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Oilers.png'),
(23, 'Vancouver', 'Canucks', 'https://nhllogos.blob.core.windows.net/nhl-logos/Canucks.png'),
(24, 'Anaheim', 'Ducks', 'https://nhllogos.blob.core.windows.net/nhl-logos/Ducks.png'),
(25, 'Dallas', 'Stars', 'https://nhllogos.blob.core.windows.net/nhl-logos/Stars.png'),
(26, 'Los Angeles', 'Kings', 'https://nhllogos.blob.core.windows.net/nhl-logos/Kings.png'),
(27, 'Phoenix', 'Coyotes', 'https://nhllogos.blob.core.windows.net/nhl-logos/PhoenixCoyotes.png'),
(28, 'San Jose', 'Sharks', 'https://nhllogos.blob.core.windows.net/nhl-logos/Sharks.png'),
(29, 'Columbus', 'Blue Jackets', 'https://nhllogos.blob.core.windows.net/nhl-logos/BlueJackets.png'),
(30, 'Minnesota', 'Wild', 'https://nhllogos.blob.core.windows.net/nhl-logos/Wild.png'),
(31, 'Minnesota', 'North Stars', 'https://nhllogos.blob.core.windows.net/nhl-logos/NorthStars.png'),
(32, 'Quebec', 'Nordiques', 'https://nhllogos.blob.core.windows.net/nhl-logos/Nordiques.png'),
(33, 'Winnipeg', 'Jets (1979)', 'https://nhllogos.blob.core.windows.net/nhl-logos/Jets1979.png'),
(34, 'Hartford', 'Whalers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Whalers.png'),
(35, 'Colorado', 'Rockies', 'https://nhllogos.blob.core.windows.net/nhl-logos/Rockies.png'),
(36, 'Ottawa', 'Senators (1917)', 'https://nhllogos.blob.core.windows.net/nhl-logos/Senators1917.png'),
(37, 'Hamilton', 'Tigers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Tigers.png'),
(38, 'Pittsburgh', 'Pirates', 'https://nhllogos.blob.core.windows.net/nhl-logos/Pirates.png'),
(39, 'Philadelphia', 'Quakers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Quakers.png'),
(40, 'Detroit', 'Cougars', 'https://nhllogos.blob.core.windows.net/nhl-logos/Cougars.png'),
(41, 'Montreal', 'Wanderers', 'https://nhllogos.blob.core.windows.net/nhl-logos/Wanderers.png'),
(42, 'Quebec', 'Bulldogs', 'https://nhllogos.blob.core.windows.net/nhl-logos/Bulldogs.png'),
(43, 'Montreal', 'Maroons', 'https://nhllogos.blob.core.windows.net/nhl-logos/Maroons.png'),
(44, 'New York', 'Americans', 'https://nhllogos.blob.core.windows.net/nhl-logos/Americans.png'),
(45, 'St. Louis', 'Eagles', 'https://nhllogos.blob.core.windows.net/nhl-logos/Eagles.png'),
(46, 'Oakland', 'Seals', 'https://nhllogos.blob.core.windows.net/nhl-logos/Seals.png'),
(47, 'Atlanta', 'Flames', 'https://nhllogos.blob.core.windows.net/nhl-logos/AtlantaFlames.png'),
(48, 'Kansas City', 'Scouts', 'https://nhllogos.blob.core.windows.net/nhl-logos/Scouts.png'),
(49, 'Cleveland', 'Barons', 'https://nhllogos.blob.core.windows.net/nhl-logos/Barons.png'),
(50, 'Detroit', 'Falcons', 'https://nhllogos.blob.core.windows.net/nhl-logos/Falcons.png'),
(51, 'Brooklyn', 'Americans', 'https://nhllogos.blob.core.windows.net/nhl-logos/BrooklynAmericans.png'),
(52, 'Winnipeg', 'Jets', 'https://nhllogos.blob.core.windows.net/nhl-logos/Jets.png'),
(53, 'Arizona', 'Coyotes', 'https://nhllogos.blob.core.windows.net/nhl-logos/Coyotes.png'),
(54, 'Vegas', 'Golden Knights', 'https://nhllogos.blob.core.windows.net/nhl-logos/GoldenKnights.png'),
(55, 'Seattle', 'Kraken', 'https://nhllogos.blob.core.windows.net/nhl-logos/Kraken.png'),
(56, 'California', 'Golden Seals', 'https://nhllogos.blob.core.windows.net/nhl-logos/GoldenSeals.png'),
(57, 'Toronto', 'Arenas', 'https://nhllogos.blob.core.windows.net/nhl-logos/Arenas.png'),
(58, 'Toronto', 'St. Patricks', 'https://nhllogos.blob.core.windows.net/nhl-logos/StPats.png')