CREATE TABLE [dbo].[FutureCleanedGame]
(
    id INT NOT NULL,
    homeTeamName VARCHAR(MAX) NOT NULL,
    awayTeamName VARCHAR(MAX) NOT NULL,
    seasonStartYear INT NOT NULL,
    gameDate Datetime NOT NULL,
    homeWinRatio FLOAT NOT NULL,
    homeRecentWinRatio FLOAT NOT NULL,
    homeRecentGoalsAvg FLOAT NOT NULL,
    homeRecentConcededGoalsAvg FLOAT NOT NULL,
    homeRecentSogAvg FLOAT NOT NULL,
    homeRecentPpgAvg FLOAT NOT NULL,
    homeRecentHitsAvg FLOAT NOT NULL,
    homeRecentPimAvg FLOAT NOT NULL,
    homeRecentBlockedShotsAvg FLOAT NOT NULL,
    homeRecentTakeawaysAvg FLOAT NOT NULL,
    homeRecentGiveawaysAvg FLOAT NOT NULL,
    homeGoalsAvg FLOAT NOT NULL,
    homeGoalsAvgAtHome FLOAT NOT NULL,
    homeRecentGoalsAvgAtHome FLOAT NOT NULL,
    homeConcededGoalsAvg FLOAT NOT NULL,
    homeConcededGoalsAvgAtHome FLOAT NOT NULL,
    homeRecentConcededGoalsAvgAtHome FLOAT NOT NULL,
    awayWinRatio FLOAT NOT NULL,
    awayRecentWinRatio FLOAT NOT NULL,
    awayRecentGoalsAvg FLOAT NOT NULL,
    awayRecentConcededGoalsAvg FLOAT NOT NULL,
    awayRecentSogAvg FLOAT NOT NULL,
    awayRecentPpgAvg FLOAT NOT NULL,
    awayRecentHitsAvg FLOAT NOT NULL,
    awayRecentPimAvg FLOAT NOT NULL,
    awayRecentBlockedShotsAvg FLOAT NOT NULL,
    awayRecentTakeawaysAvg FLOAT NOT NULL,
    awayRecentGiveawaysAvg FLOAT NOT NULL,
    awayGoalsAvg FLOAT NOT NULL,
    awayGoalsAvgAtAway FLOAT NOT NULL,
    awayRecentGoalsAvgAtAway FLOAT NOT NULL,
    awayConcededGoalsAvg FLOAT NOT NULL,
    awayConcededGoalsAvgAtAway FLOAT NOT NULL,
    awayRecentConcededGoalsAvgAtAway FLOAT NOT NULL,
    PRIMARY KEY(id),
)
