CREATE TABLE [dbo].[Game]
(
    id INT NOT NULL,
    homeTeamName VARCHAR(MAX) NOT NULL,
    awayTeamName VARCHAR(MAX) NOT NULL,
    seasonStartYear INT NOT NULL,
    gameDate DATETIME2 NOT NULL,
    homeGoals INT NOT NULL,
    awayGoals INT NOT NULL,
    winner INT NOT NULL,
    homeSOG INT NOT NULL,
    awaySOG INT NOT NULL,
    homePPG INT NOT NULL,
    awayPPG INT NOT NULL,
    homePIM INT NOT NULL,
    awayPIM INT NOT NULL,
    homeFaceOffWinPercent DECIMAL(6, 3) NOT NULL,
    awayFaceOffWinPercent DECIMAL(6, 3) NOT NULL,
    homeBlockedShots INT NOT NULL,
    awayBlockedShots INT NOT NULL,
    homeHits INT NOT NULL,
    awayHits INT NOT NULL,
    homeTakeaways INT NOT NULL,
    awayTakeaways INT NOT NULL,
    homeGiveaways INT NOT NULL,
    awayGiveaways INT NOT NULL,
    PRIMARY KEY(id),
)
